// https://github.com/manna-harbour/qmk_firmware/blob/crkbd/keyboards/crkbd/keymaps/manna-harbour/readme.org

#pragma once

// Space optimization
#define LAYER_STATE_8BIT

#define MASTER_RIGHT

// Split data transport
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_WPM_ENABLE

// Matrix
/*#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define RGB_DI_PIN D3    // LED data pin

#ifdef RGBLIGHT_ENABLE
#define RGBLED_NUM 12    // Number of LEDs
#endif
#ifdef RGB_MATRIX_ENABLE
#define RGBLED_NUM 54    // Number of LEDs
#define DRIVER_LED_TOTAL RGBLED_NUM
#endif
*/

// Trackpoint module
#if defined MH_MODULE_TRACKPOINT && defined PS2_MOUSE_ENABLE
  // clock on pin 1 (d0, int0)
  #define PS2_CLOCK_PORT PORTD
  #define PS2_CLOCK_PIN PIND
  #define PS2_CLOCK_DDR DDRD
  #define PS2_CLOCK_BIT 0  // data pin 1
  #define PS2_INT_INIT() do { EICRA |= ((1<<ISC01) | (0<<ISC00)); } while (0)
  #define PS2_INT_ON() do { EIMSK |= (1<<INT0); } while (0)
  #define PS2_INT_OFF() do { EIMSK &= ~(1<<INT0); } while (0)
  #define PS2_INT_VECT INT0_vect
  // data on pin 2 (d1)
  #define PS2_DATA_PORT PORTD
  #define PS2_DATA_PIN PIND
  #define PS2_DATA_DDR DDRD
  #define PS2_DATA_BIT 1  // data pin 2
  #define PS2_MOUSE_ROTATE 90 // compensate for west-facing device orientation
  #define PS2_MOUSE_SCROLL_BTN_MASK (1 << PS2_MOUSE_BTN_MIDDLE)
  //#define PS2_MOUSE_SCROLL_BTN_SEND TAPPING_TERM
  #define PS2_MOUSE_SCROLL_DIVISOR_V 5
  #define PS2_MOUSE_SCROLL_DIVISOR_H PS2_MOUSE_SCROLL_DIVISOR_V
#endif

//#if defined MH_AUTO_BUTTONS
// Non-master controller needs to know about these too
  #define MH_AUTO_BUTTONS_LAYER 4
  #define MH_AUTO_BUTTONS_TIMEOUT 300
//#endif

#if !defined MH_LOW_MOUSE && defined PS2_MOUSE_ENABLE
  // sensitivity
  #define PS2_MOUSE_X_MULTIPLIER 8
  #define PS2_MOUSE_Y_MULTIPLIER 8
  #define PS2_MOUSE_USE_2_1_SCALING
  #define MK_KINETIC_SPEED 1
  #define MOUSEKEY_INTERVAL 16  // for 60Hz refresh
#endif

#if defined MH_LOW_MOUSE && defined MOUSEKEY_ENABLE
  #undef MOUSEKEY_TIME_TO_MAX
  #define MOUSEKEY_TIME_TO_MAX 128
#endif

#if defined MH_LOW_MOUSE
  #undef PRODUCT
  #define PRODUCT Corne Keyboard (crkbd) with low rate mouse
#endif

#if defined OLED_DRIVER_ENABLE
  #define OLED_TIMEOUT 30000 // ms
  #define MH_OLED_TIMEOUT
#endif

#if defined RGB_MATRIX_ENABLE
  #define RGB_MATRIX_KEYPRESSES
  #define RGB_MATRIX_FRAMEBUFFER_EFFECTS
  #define RGB_DISABLE_WHEN_USB_SUSPENDED true
  #define RGB_MATRIX_MAXIMUM_BRIGHTNESS 120
  #define RGB_MATRIX_HUE_STEP 8
  #define RGB_MATRIX_SAT_STEP 8
  #define RGB_MATRIX_VAL_STEP 8
  #define RGB_MATRIX_SPD_STEP 10
  #define MH_RGB_TOGGLE_OFF
#else
  #undef ENABLE_RGB_MATRIX_ALPHAS_MODS
  #undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
  #undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
  #undef ENABLE_RGB_MATRIX_BREATHING
  #undef ENABLE_RGB_MATRIX_BAND_SAT
  #undef ENABLE_RGB_MATRIX_BAND_VAL
  #undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
  #undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
  #undef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
  #undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
  #undef ENABLE_RGB_MATRIX_CYCLE_ALL
  #undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
  #undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
  #undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
  #undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
  #undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
  #undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
  #undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
  #undef ENABLE_RGB_MATRIX_DUAL_BEACON
  #undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
  #undef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
  #undef ENABLE_RGB_MATRIX_RAINDROPS
  #undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
  #undef ENABLE_RGB_MATRIX_HUE_BREATHING
  #undef ENABLE_RGB_MATRIX_HUE_PENDULUM
  #undef ENABLE_RGB_MATRIX_HUE_WAVE
  #undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
  #undef ENABLE_RGB_MATRIX_PIXEL_FLOW
  #undef ENABLE_RGB_MATRIX_PIXEL_RAIN
  
  #undef ENABLE_RGB_MATRIX_TYPING_HEATMAP
  #undef ENABLE_RGB_MATRIX_DIGITAL_RAIN
  
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
  #undef ENABLE_RGB_MATRIX_SPLASH
  #undef ENABLE_RGB_MATRIX_MULTISPLASH
  #undef ENABLE_RGB_MATRIX_SOLID_SPLASH
  #undef ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
#endif

#if defined RGBLIGHT_ENABLE
  #undef RGBLED_NUM
  #if defined MH_RGB_UNDERGLOW
    #define RGBLED_NUM 6
  #else
    #define RGBLED_NUM 27
  #endif
  #define RGBLIGHT_SLEEP
  #define RGBLIGHT_LIMIT_VAL 120
  #define RGBLIGHT_HUE_STEP 8
  #define RGBLIGHT_SAT_STEP 8
  #define RGBLIGHT_VAL_STEP 8
  #define RGBLIGHT_ANIMATIONS
  #define RGBLIGHT_SPLIT
#else
  #undef RGBLIGHT_ANIMATIONS
  #undef RGBLIGHT_EFFECT_BREATHING
  #undef RGBLIGHT_EFFECT_RAINBOW_MOOD
  #undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
  #undef RGBLIGHT_EFFECT_SNAKE
  #undef RGBLIGHT_EFFECT_KNIGHT
  #undef RGBLIGHT_EFFECT_CHRISTMAS
  #undef RGBLIGHT_EFFECT_STATIC_GRADIENT
  #undef RGBLIGHT_EFFECT_RGB_TEST
  #undef RGBLIGHT_EFFECT_ALTERNATING
  #undef RGBLIGHT_EFFECT_TWINKLE
#endif

#if defined MH_DEBUG
  #define PS2_MOUSE_DEBUG_RAW
#endif
